# Bicycle Trip: Cumulative and Daily Miles

## Introduction

This notebook uses a pandas Series to store the cumulative miles recorded at the end of each day of a bicycle trip from New York City to Key West, Florida.

The cumulative mileage can then be used to determine the total number of miles ridden each day.

In addition, the mileage values used in this notebook are example data created for demonstrating the calculations.

In [4]:
import pandas as pd

cumulative_miles = [55, 120, 195, 280, 370, 465, 570, 680, 795, 915, 1040, 1165, 1290, 1445]

In [5]:
mileage_series = pd.Series (cumulative_miles)

print (mileage_series)

0       55
1      120
2      195
3      280
4      370
5      465
6      570
7      680
8      795
9      915
10    1040
11    1165
12    1290
13    1445
dtype: int64


## Cumulative Mileage

The pandas Series contains the cumulative number of miles recorded at the end of each day.

For example, the value 55 represents the total miles on the odometer at the end of Day 1, while 120 represents the total miles at the end of Day 2.

To determine the miles ridden on each day, we can subtract the previous day's cumulative mileage from the current day's cumulative mileage.

In [7]:
daily_miles = mileage_series.diff()
daily_miles.iloc[0] = mileage_series.iloc[0]
daily_miles = daily_miles.astype(int)

daily_miles.index = [f"Day {i}" for i in range(1, len(daily_miles) + 1)]

print (daily_miles)

Day 1      55
Day 2      65
Day 3      75
Day 4      85
Day 5      90
Day 6      95
Day 7     105
Day 8     110
Day 9     115
Day 10    120
Day 11    125
Day 12    125
Day 13    125
Day 14    155
dtype: int64


## Miles Ridden Each Day

The daily miles are calculated by subtracting the previous day's cumulative mileage from the current day's cumulative mileage.

For Day 1, the cumulative mileage is 55 miles, so the daily mileage is also 55 miles. For each following day, the difference between the two cumulative mileage readings gives the number of miles ridden that day.

The daily mileage values add up to a total of 1,445 miles for the entire trip.

In [8]:
trip_summary = pd.DataFrame({
    "Cumulative Miles": mileage_series.values,
    "Miles Ridden": daily_miles.values
})

trip_summary.index = [f"Day {i}" for i in range(1, len(trip_summary) + 1)]

print (trip_summary)

        Cumulative Miles  Miles Ridden
Day 1                 55            55
Day 2                120            65
Day 3                195            75
Day 4                280            85
Day 5                370            90
Day 6                465            95
Day 7                570           105
Day 8                680           110
Day 9                795           115
Day 10               915           120
Day 11              1040           125
Day 12              1165           125
Day 13              1290           125
Day 14              1445           155


## Conclusion

The pandas Series stores the cumulative mileage recorded at the end of each day. By comparing each day's cumulative mileage with the previous day's mileage, we can determine the total miles ridden each day.

The trip in this example covers a total of 1,445 miles over 14 days.